### ISSUE TITLE
Could not add Video

### ISSUE THREAD

**Issue by TiloDroid** [asusguy94/Porn-Organizer#5]
Hello, 
I tried to set up this project with wamp following the instructions and now I want to add videos. But instead of adding the video, I get the following result:
![image](https://user-images.githubusercontent.com/67080540/84962611-8ad00f00-b107-11ea-9c05-a1dcdc96b5a3.png)
What did I do wrong?

**Desktop:**
 - OS: [e.g. Windows 10]
 - Browser [Google Chrome]

**Comment by asusguy94** [comment]
seems like it is a folder issue, how is the folder structure setup within your web server...at what path is the file you're trying to add placed?

**Comment by asusguy94** [comment]
`FFMPEG` & `FFPROBE` is required to be installed in addition and the path linked within this project...have you done that?

**Comment by TiloDroid** [comment]
I've installed FFMPEG and FFPROBE into a folder on my external hard drive, so I entered 'K:\FFMPEG' (the name of the folder) into the _class.php file. Concerning the folder structure, since I use wamp I pasted the project files into the www folder to access it via the localhost hyperlink. The video follows the following direction: "K:\wamp\www\videos\b\{2001-02-16} [Teen] Blonde_number one". I'm not experienced with wamp, so maybe simply pasting the whole project into the www might have been a mistake? If there's any more useful information I could provide, please inform me.

**Comment by asusguy94** [comment]
Is there a spelling error in your folder structure?
is `K:\wamp\www\videos\b{2001-02-16} [Teen] Blonde_number one` the path of this file,
or is `"K:\wamp\www\videos\b\{2001-02-16} [Teen] Blonde_number one.mp4` correct?

also, the ffmpeg and ffprobe needs to have the file (not just the folder)...so you will need to write `K:\FFMPEG\ffmpeg` and `K:\FFMPEG\ffprobe`

Also, visiting **debug.php** in the browser might give some info about what is wrong...you will have to re-download the project again...or optionally just downloading [debug.php](https://raw.githubusercontent.com/asusguy94/Porn-Organizer/v2/debug.php) and move it inside the project

**Comment by asusguy94** [comment]
Hm...it seems like I've used some code that is exclusive to *Linux*, and I'm not sure this is what is causing the error. I'm creating a patch now, this and the steps above will fix the problem.

**Comment by TiloDroid** [comment]
![image](https://user-images.githubusercontent.com/67080540/85413032-9178df00-b56a-11ea-8719-d4081d89d741.png)
This is what my Debug.php looks like in the browser. I've changed the directions in the _class.php file to 'K:\FFMPEG\ffprobe.exe' and 'K:\FFMPEG\ffmpeg.exe'. I'm looking forward to your patch.

**Comment by asusguy94** [comment]
Also...keep in mind that scrollbar-thumbnails will not work, unless you also link imagemagic...in the same way as ffmpeg and ffprobe.

**Comment by TiloDroid** [comment]
I've now updated my _class.php file while also copying the file directions and database information from the old file. However, my index looks like this now: 
![image](https://user-images.githubusercontent.com/67080540/85418975-cb011880-b571-11ea-84ad-caf09ed4b278.png)
![image](https://user-images.githubusercontent.com/67080540/85419066-e4a26000-b571-11ea-9c9e-1aa2373990f3.png)
![image](https://user-images.githubusercontent.com/67080540/85419097-eff58b80-b571-11ea-9c50-12a6ad1fa797.png)
The added video plays fine tho.

**Comment by TiloDroid** [comment]
Also, the Debug.php page shows this notice: 
![image](https://user-images.githubusercontent.com/67080540/85419300-321ecd00-b572-11ea-91b2-029378c55fc2.png)

**Comment by asusguy94** [comment]
Notice is just a fancy way PHP says that something **might** be wrong, you can actually disable them by finding the php.ini file (inside the wamp folder) and changing `error_reporting = E_ALL` to `error_reporting = E_ALL & ~E_NOTICE`

`E_ALL` is used for development and by default, and `E_ALL & ~E_NOTICE` is used for production

**Comment by asusguy94** [comment]
when it comes to `enable_dash`, it is probably because the settings table is incorrect...best way would be to log into phpmyadmin (click on DB in the app) and go into the databaseName->settings, then look for a row-heading called enable_dash

If you can find no such row, it the table is probably not working as it should, you then have 2 choices.
1. change `define('enableDASH', $opt['enable_dash']);` to `define('enableDASH', false);`. This will make it so, DASH is always disabled...but if you want to use it later, you have to manually enable it through this script. Also, if you later download '_class.php' you will probably have to do this again.
2. Re-Import [database.sql](DATABASE.sql-URL). This will allow the database to run as intended. And will probably fix the problem for good. Only downside is that it might wipe the current database, so I recomend making a copy of the database before you do this.

If you do have the row in the database-table, there is probably an issue with the data of the row. If you have **not** initialized settings from the settings page on the app, **do that first**, then you can check back to see if there is any change. If the table get's initialized without any data in the row, you can set the data to 0 or 1...then the settings page should work again.

*Keep in mind, that since all of these are **Notices**, just doing nothing about it might work just fine.*

**Comment by asusguy94** [comment]
It is **Important** that you setup settings.php...as it will set initial settings for the app
